import React from 'react';
import { Page, Text, View, Document, StyleSheet, PDFViewer, Image } from '@react-pdf/renderer';
import { useInvoiceStore } from '../store/invoiceStore';
import { CURRENCIES } from '../types';

const styles = StyleSheet.create({
  viewer: {
    width: '100%',
    height: '500px',
  },
  page: {
    padding: 50,
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: '#334155',
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#334155',
    textTransform: 'uppercase',
  },
  logo: {
    width: 50,
    height: 50,
  },
  section: {
    marginBottom: 20,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  label: {
    fontSize: 12,
    color: '#64748b',
    width: 120,
  },
  value: {
    fontSize: 14,
    color: '#334155',
    flex: 1,
  },
  amount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#334155',
    marginTop: 20,
  },
  paymentSection: {
    marginTop: 40,
    padding: 20,
    backgroundColor: '#f8fafc',
    borderRadius: 4,
  },
  paymentTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#334155',
    marginBottom: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 50,
    left: 50,
    right: 50,
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 10,
  },
});

export function InvoicePreview() {
  const { invoice } = useInvoiceStore();
  const currencySymbol = CURRENCIES.find(c => c.code === invoice.currency)?.symbol || '$';

  return (
    <PDFViewer style={styles.viewer}>
      <Document>
        <Page size="A4" style={styles.page}>
          <View style={styles.header}>
            <Text style={styles.title}>Invoice</Text>
            <Image
              style={styles.logo}
              src="https://images.unsplash.com/photo-1633409361618-c73427e4e206?auto=format&fit=crop&w=100&q=80"
            />
          </View>

          <View style={styles.section}>
            <View style={styles.row}>
              <Text style={styles.label}>Client Name:</Text>
              <Text style={styles.value}>{invoice.clientName}</Text>
            </View>

            <View style={styles.row}>
              <Text style={styles.label}>Client Email:</Text>
              <Text style={styles.value}>{invoice.clientEmail}</Text>
            </View>

            <View style={styles.row}>
              <Text style={styles.label}>Date:</Text>
              <Text style={styles.value}>{new Date(invoice.date).toLocaleDateString()}</Text>
            </View>

            <View style={styles.row}>
              <Text style={styles.label}>Description:</Text>
              <Text style={styles.value}>{invoice.description}</Text>
            </View>

            <Text style={styles.amount}>
              Amount: {currencySymbol}{invoice.amount}
            </Text>
          </View>

          {invoice.paymentMethod && (
            <View style={styles.paymentSection}>
              <Text style={styles.paymentTitle}>Payment Information</Text>
              <Text style={styles.value}>
                Please pay via {invoice.paymentMethod === 'stripe' ? 'Stripe' : 'PayPal'}
              </Text>
              {invoice.paymentMethod === 'paypal' && invoice.paypalEmail && (
                <Text style={styles.value}>PayPal: {invoice.paypalEmail}</Text>
              )}
            </View>
          )}

          <Text style={styles.footer}>
            Generated by VoiceInvoice • {new Date().toLocaleDateString()}
          </Text>
        </Page>
      </Document>
    </PDFViewer>
  );
}